// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["jquery", "underscore", "backbone", "handlebars", "text!./../templates/signup.hbs", "text!./../templates/message.hbs"], function($, _, Backbone, Handlebars, signupTemplate, messageTemplate) {
    'use strict';
    var SignupView, _ref;

    return SignupView = (function(_super) {
      __extends(SignupView, _super);

      function SignupView() {
        this.handleUpload = __bind(this.handleUpload, this);        _ref = SignupView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      SignupView.prototype.el = "#container";

      SignupView.prototype.events = {
        "submit #signup-form": "handleSubmit",
        "click .close": "closeAlert"
      };

      SignupView.prototype.template = Handlebars.compile(signupTemplate);

      SignupView.prototype.initialize = function() {
        Handlebars.registerPartial("message", messageTemplate);
        return this.render();
      };

      SignupView.prototype.render = function() {
        return $(this.el).html(this.template);
      };

      SignupView.prototype.handleSubmit = function(e) {
        e.preventDefault();
        return $("#signup-form").ajaxSubmit({
          success: this.handleUpload
        });
      };

      SignupView.prototype.handleUpload = function(response, status, xhr, form) {
        return $(this.el).html(this.template(_.extend(response, {
          page: "signup"
        })));
      };

      SignupView.prototype.closeAlert = function(e) {
        var _ref1;

        e.preventDefault();
        return (_ref1 = $(".alert-box")) != null ? _ref1.fadeOut() : void 0;
      };

      return SignupView;

    })(Backbone.View);
  });

}).call(this);
