// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["jquery", "backbone", "app/views/login", "app/views/home", "app/views/graph", "app/models/salesdata", "app/collections/salesdatacollection"], function($, Backbone, LoginView, HomeView, GraphView, SalesData, SalesDataCollection) {
    var AppRouter, _ref;

    return AppRouter = (function(_super) {
      __extends(AppRouter, _super);

      function AppRouter() {
        _ref = AppRouter.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      AppRouter.prototype.routes = {
        "": "index",
        "login": "home",
        "graph": "graph"
      };

      AppRouter.prototype.index = function() {
        return new LoginView();
      };

      AppRouter.prototype.home = function() {
        return new HomeView();
      };

      AppRouter.prototype.graph = function() {
        var salesdata, salesdataCollection;

        salesdata = new SalesData();
        salesdataCollection = new SalesDataCollection();
        return new GraphView({
          model: salesdata,
          collection: salesdataCollection
        });
      };

      return AppRouter;

    })(Backbone.Router);
  });

}).call(this);
